<script>
    var descriArr = {};
    descriArr["cancel"]="<?=$this->lang->line('cancel');?>";
    descriArr["trace"]="<?=$this->lang->line('trace');?>";
    descriArr["traced"]="<?=$this->lang->line('traced');?>";
    descriArr["loading"]="<?=$this->lang->line('post_loading');?>";
    descriArr["fullload"]="<?=$this->lang->line('post_full_load');?>";
    descriArr["maxuploadnum"]="<?=$this->lang->line('upload_exceed_max_pic_num');?>";
    descriArr["mv_maxuploadsize"]="<?=$this->lang->line('upload_exceed_max_movie_size');?>";
    descriArr["pic_maxuploadsize"]="<?=$this->lang->line('upload_exceed_max_pic_zise');?>";
    descriArr["edit_avatar"]="<?=$this->lang->line('member_edit_avatar');?>";
    descriArr["edit_cover"]="<?=$this->lang->line('member_edit_cover');?>";
    descriArr["no_invite"]="<?=$this->lang->line('no_invite')?>";
    descriArr["friend_invite"]="<?=$this->lang->line('friend_invite')?>";
    descriArr["friend_invited"]="<?=$this->lang->line('friend_invited')?>";
    descriArr["post_more"]="<?=$this->lang->line('post_more')?>";
    descriArr["post_collapse"]="<?=$this->lang->line('post_collapse')?>";
    descriArr["chat"]="<?=$this->lang->line('chat')?>";
    descriArr["friend_invited"]="<?=$this->lang->line('friend_invited')?>";
    descriArr["friend_invite"]="<?=$this->lang->line('friend_invite')?>";
    descriArr["share_success"]="<?=$this->lang->line('share_success')?>";
</script>